# Lidar2OSM Processing Configuration

main_bag_directory_path: "/root/datasets/CU_MULTI/bags/ros1"
main_output_directory_path:  "/root/datasets/CU_MULTI"
generate_sequence_run_stats: false
display_rosbag_data: false

sequences:
  kittredge_loop: 
    sequence_bag_path: "/root/datasets/CU_MULTI/bags/ros1"
    binarized_sub_dir: "/root/datasets/CU_MULTI/kittredge_loop/binarized"
    robots: [1]

  # main_campus: 
  #   robots: [1]